id: P00994A3C
initial_creation_type: input
source_metadata:
  title: Guru Padmasambhava
  language: fr
  description: 'Prayers to the Precious Guru Padmasambhava or Padmākara (padma ''byung
    gnas), the "Lotus-Born", who is credited with establishing Buddhism in Tibet:'
  volume:
    9046278a20494675b386bca599c35646:
      title: A Synopsis of Guru Padmasambhava’s Life
      parent: Alak Zenkar Pema Ngödrup Rolwe Dorje
    80c6b2536f224e52994ab6784cb95e50:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Dudjom Rinpoche
    4a3f3c1912cb4b7faeb2458b08610878:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Chokgyur Dechen Lingpa
    34f6d463184840e590d4a5ed5dc392fa:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    a6ab37b3c4984e84878734e7fbbfbaff:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    328b37d530654be6af502eb2be92ea50:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Chokgyur Dechen Lingpa
    11a3a95da3ea4e0b9cbf3d9577131ba3:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    25669822a73b422d9c7b4513dbc50b81:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    a2bdf4d7a1fd47b3a972b473fec3615c:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    f2d7404fae4d4ea4bd044f4106b71296:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Chokgyur Dechen Lingpa
    1f83ba91487a429b91158a4757830b2c:
      title: 'A Garland of Vajra Words: A Prayer to the Guru'
      parent: Dilgo Khyentse Rinpoche
    f28b20a8ab8d4a9c97fbb45c4b5267e7:
      title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in
        Eight Chapters'
      parent: Dilgo Khyentse Rinpoche
    752e17220c1241ee976f9c77be12e873:
      title: The Prayer to Swiftly Fulfil All Wishes
      parent: Dilgo Khyentse Rinpoche
    33ec4b71db7a4140aeda12e648d813ac:
      title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
      parent: Dilgo Khyentse Rinpoche
    af65eb191f8c4245a806508b1ae66753:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    959fabeb3ba7480a8f57d69f2c7dd78d:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    a7711d1ef7bc4388bf940c20e0817dc6:
      title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
      parent: Dodrupchen Jigme Tenpe Nyima
    643c53e6b3184c898da63454a96beab7:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Dodrupchen Jigme Tenpe Nyima
    9526e33ee9364b1587ccb5218d23f9b0:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    480ad11c9a1241ad87cd2ef6f4278eeb:
      title: A Prayer to Padmasambhava
      parent: Dudjom Lingpa
    2ec62e5126d8406da6816c31d291dc08:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Dudjom Rinpoche
    b55a4e260c7f47fa81f22affa190e79e:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Dudjom Rinpoche
    a5f8f592c96a4acab436a4c29a4896f2:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Dudjom Rinpoche
    20e48123b286438eb8fa347c1ec4886c:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Dudjom Rinpoche
    21bf8bf4d4ab4290b752c14323a6ae6b:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Dudjom Rinpoche
    f0ddaffce0a54e00bd691e6ff03987e5:
      title: A Prayer to the Precious Guru from Uḍḍiyāna That Spontaneously Fulfils
        All Wishes
      parent: Dzongter Kunzang Nyima
    aff380f78ccb4b64be21bdcb773b3934:
      title: 'Cloud Banks of Blessings: A Prayer to Guru Padmasambhava'
      parent: Fifth Dalai Lama
    ab785190d65b4925bb1d1efde92fe142:
      title: A Yearning Song of Prayer to Invoke the Wisdom Mind of the Compassionate
        Teacher Padmasambhava
      parent: Fourteenth Dalai Lama
    b1f3da923673473893e416266c6476c3:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    7eb58fafc9d549be834c157881631751:
      title: Prayer to Orgyen Rinpoche Invoking His Wisdom Mind
      parent: Gönpo Tseten Rinpoche
    18ed0c489be74ea7a962f28967d61b66:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Jamgön Kongtrul
    952adba3bba04f08a5e89ff2507cd569:
      title: A Heart Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    675cd2fc602a4b6e9c744ef7d49f4706:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Jamyang Khyentse Chökyi Lodrö
    98a4592ebf9e4fb4a89f9efe35740242:
      title: A Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    0577a040618543eb80a2e4c2f684d4e2:
      title: A Yearning Plea to the Precious Guru
      parent: Jamyang Khyentse Chökyi Lodrö
    ea90377033004698bef4fb3883db7125:
      title: 'Cloud Banks of Blessings: A Prayer to Orgyen Rinpoche'
      parent: Jamyang Khyentse Chökyi Lodrö
    44b931dd94e6411da421b2c8728aa6df:
      title: Prayer of the Wisdom Mind
      parent: Jamyang Khyentse Chökyi Lodrö
    94213afccce74da3b65613f1e3335cad:
      title: Spontaneous Fulfilment of Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    641fcfab97674901ab045f8a01bf3721:
      title: The Falling Elixir of Blessing
      parent: Jamyang Khyentse Chökyi Lodrö
    62f27e992c464dc8bfbef0f18573128b:
      title: 'The Fulfilment of Wishes and Aspirations: A Prayer to Ācārya Padmasambhava'
      parent: Jamyang Khyentse Chökyi Lodrö
    6e6fc89b499d495e95923a81e1736669:
      title: 'The Supreme Bestowal of Twofold Attainment: A Prayer to Orgyen Rinpoche,
        Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Chökyi Lodrö
    12e77c856d6a4e46b011a7a6d841cb2f:
      title: 'The Swift Fulfilment of Aspirations: A Prayer to Glorious Orgyen, King
        of Dharma'
      parent: Jamyang Khyentse Chökyi Lodrö
    57ffdfceb7404327aa0f098abccaa2d4:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Jamyang Khyentse Chökyi Lodrö
    408ddf3d8831428995879402e8b7ad64:
      title: To Fulfil All Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    61c4edee41274eb6b02910224599a7c9:
      title: Turning Back the Misfortunes of the Age of Degeneration
      parent: Jamyang Khyentse Chökyi Lodrö
    d313b114512e447fa0aa2617101612ef:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Jamyang Khyentse Wangpo
    bdfe467a8b4a425ba8cffe623a125163:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    6bb652b57f5d4d89b3e87ddb04467abb:
      title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling
        to the Realm of Lotus Light'
      parent: Jamyang Khyentse Wangpo
    7b765c7ec8394a5ea63abdf84e095c41:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    9a308dc4e1f443ad92f192cfcb7b2769:
      title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche
        and the Twenty-Five Disciples, the King and Subjects'
      parent: Jamyang Khyentse Wangpo
    9b9b1119137b4ea48f59e99d9104c727:
      title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen
        Rinpoche, Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Wangpo
    8bcb2600de7648b7962d0524a634d00a:
      title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
        the Precious Master of Oddiyana'
      parent: Jamyang Khyentse Wangpo
    d2caf814af5b4c2db0f16d5e5031b4e2:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Jigme Lingpa
    46801bdde0a744c88b7bef15258d3866:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Jigme Lingpa
    164cbd5fc7fb401c981a8a3a90614b8d:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    a8ff0244e9cd4d7fa81cf56807cd40d0:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Jigme Lingpa
    f4357c00f0ec4807ade9fa845bb7e99c:
      title: Prayer to Pema Tötreng Tsal
      parent: Khenchen Ngawang Palzang
    81892af894cc4ae9810acb2308a46244:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Longchen Rabjam
    c042cd0629a94b7ba1276f68a0760b3c:
      title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
      parent: Menlungpa Mikyö Dorje
    548ed0d05b2e40aea2c6664ea5b2f8b6:
      title: A Plaintive Prayer to Guru Rinpoche
      parent: Minling Chung Rinpoche
    94672c01a6dc4d8e8d3f0f51a0c1008c:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Mipham Rinpoche
    400cadfb8b0b449db4195fd83d875d17:
      title: Recollecting the Deeds of The Tenth Days
      parent: Mipham Rinpoche
    f17e7627c8634217a0d09ed91c649bc9:
      title: The Prayer which is the Source of All True Realization
      parent: Mipham Rinpoche
    8ece48f5105d4fc2bf7ff12f63182b73:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Mipham Rinpoche
    fe6e18c151e141d88dd1139e12147ee6:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    de762bda75b54c16882c74b374fdd6b4:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    0ff781183eb94546a47f454c035d5077:
      title: The Prayer to Orgyen Rinpoche that Invokes the Heart of his Wisdom Mind
      parent: Pawo Lerab Tsal
    e792d27f371b46cc8cc3f555a45f0b16:
      title: An Extremely Concise Barché Lamsel—The Prayer for Clearing Obstacles
        from the Path
      parent: Rangrik Dorje
    a7b74321e4794c0dbb62877f58702f2b:
      title: An Extremely Concise Sampa Lhundrup—Prayer that Spontaneously Fulfils
        All Wishes
      parent: Rangrik Dorje
    d0dc3f4ec99643c7aa797c79004b4baa:
      title: The Seven Lines that Dispel All Obstacles and Enfold All Profundity
      parent: Rangrik Dorje
    08918559c8854c469177da7c1e1f46a9:
      title: 'The Spontaneous Fulfilment of All Wishes: Invoking the Great Guru of
        Uḍḍiyāna'
      parent: Rangrik Dorje
    dff526328fbb4f358df98b3c54088b69:
      title: 'The Wish-Fulfilling Tree: A Prayer to the All-Embodying Lama Tsokye
        Dorje'
      parent: Rangrik Dorje
    7bef56e075eb4c67b1dfbebce5407f6c:
      title: 'Victory Over All Adversity: A Prayer to Invoke Guru Rinpoche’s Wisdom
        for the Swift Fulfilment of Wishes'
      parent: Rangrik Dorje
    bbccc54d99814ff7b34235f3fc1fcff8:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Ratna Lingpa
    56c50a2bfa714e0ba7aabd41404f5a56:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Ratna Lingpa
    548e1b0b033f4fec9fe96d8b1f4926f1:
      title: A Prayer To Padmasambhava
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    c9ee90533421433d846417240857bbd6:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    8e96616952534d0fa43aec89ee508f95:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Shechen Rabjam Rinpoche
    89937b36be274dab82c1c79cfbf788ac:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Outlines
created_at: '2022-03-01T03:50:02.048790'
last_modified_at: '2022-03-01T03:50:02.048793'
